Repository team-haribo/GOMS-Android, pull requests merged in 2023-06, with the labels that each got.

#136 🔀 :: (#135) - Update README.md
  README.md
Labels: refactoring

#137 🔀 :: (#133) - 학생 관리하기 text 잘리던 문제 해결
  presentation/src/main/res/layout/fragment_home.xml
Labels: fix

#142 🔀 :: (#143) 1.0.3 업데이트
  data/build.gradle.kts
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
  presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_sign_in.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_qr_scan.xml
Labels: release
