Repository team-haribo/GOMS-Android, pull requests merged in 2023-07, with the labels that each got.

#150 🔀 :: (#147) 메인 새로고침 로직
  buildSrc/.gitignore
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/res/layout/fragment_home.xml
Labels: feature

#155 🔀 :: (#149) - 관리자 필터가 새로고침되지 않던 오류 수정
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/SearchFilterBottomSheetDialog.kt
  presentation/src/main/java/com/goms/presentation/view/manage/data/UserFilterOptions.kt
  presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
Labels: bug

#157 🔀 :: (#156) - 필터 초기화를 눌렀을 때 선택되었던 값이 남아있던 오류 수정
  .idea/misc.xml
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/SearchFilterBottomSheetDialog.kt
Labels: fix

#158 🔀 :: (#153) - 외출 학생 삭제
  data/src/main/java/com/goms/data/api/CouncilApi.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/UserMapper.kt
  data/src/main/java/com/goms/data/model/user/UserResponse.kt
  data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/user/UserResponseData.kt
  domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
  domain/src/main/java/com/goms/domain/usecase/admin/DeleteOutingUseCase.kt
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
  presentation/src/main/res/drawable/delete_button_bg.xml
Labels: feature

#159 🔀 :: (#152) 외출 학생 검색
  .idea/.gitignore
  .idea/discord.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/sonarlint/issuestore/0/5/05efc8b1657769a27696d478ded1e95f38737233
  .idea/sonarlint/issuestore/0/9/09764b05ab06b0bb83420b686d2586e7c0f3d50d
  .idea/sonarlint/issuestore/3/5/3511f000fb254bf4f7160df083126128958b7118
  .idea/sonarlint/issuestore/b/2/b28cd18ae20bb712c875141ee5692cbb38fe2d76
  .idea/sonarlint/issuestore/f/b/fbca453880d1e4bf85dee45541fc678b5da70bdf
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/0/5/05efc8b1657769a27696d478ded1e95f38737233
  .idea/sonarlint/securityhotspotstore/0/9/09764b05ab06b0bb83420b686d2586e7c0f3d50d
  .idea/sonarlint/securityhotspotstore/3/5/3511f000fb254bf4f7160df083126128958b7118
  .idea/sonarlint/securityhotspotstore/b/2/b28cd18ae20bb712c875141ee5692cbb38fe2d76
  .idea/sonarlint/securityhotspotstore/f/b/fbca453880d1e4bf85dee45541fc678b5da70bdf
  .idea/sonarlint/securityhotspotstore/index.pb
  .idea/vcs.xml
  build.gradle.kts
  data/src/main/java/com/goms/data/api/OutingApi.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
  data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
  domain/src/main/java/com/goms/domain/usecase/outing/OutingStudentSearchUseCase.kt
  presentation/google-services.json.gpg
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
  presentation/src/main/res/drawable/search_edit_text_background.xml
  presentation/src/main/res/layout/fragment_outing.xml
Labels: feature

#160 🔀 :: (#146) - 권한 변경 시 뷰 자동으로 변경되게 수정
  .idea/compiler.xml
  .idea/misc.xml
  data/src/main/java/com/goms/data/api/LateApi.kt
  data/src/main/java/com/goms/data/datasource/late/LateDataSource.kt
  data/src/main/java/com/goms/data/datasource/late/LateDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/AuthMapper.kt
  data/src/main/java/com/goms/data/mapper/LateMapper.kt
  data/src/main/java/com/goms/data/mapper/ProfileMapper.kt
  data/src/main/java/com/goms/data/model/late/LateUserResponse.kt
  data/src/main/java/com/goms/data/model/profile/ProfileResponse.kt
  data/src/main/java/com/goms/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/goms/data/repository/LateRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/auth/response/RefreshTokenResponseData.kt
  domain/src/main/java/com/goms/domain/data/late/LateUserResponseData.kt
  domain/src/main/java/com/goms/domain/data/profile/ProfileResponseData.kt
  domain/src/main/java/com/goms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/goms/domain/repository/LateRepository.kt
  domain/src/main/java/com/goms/domain/usecase/auth/RefreshTokenUseCase.kt
  domain/src/main/java/com/goms/domain/usecase/late/LateUseCase.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/home/component/HomeItemCard.kt
  presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/SplashViewModel.kt
Labels: fix

#166 🔀 :: (#165) LazyColumn PullScroll 고정 오류 해결
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/res/layout/fragment_outing.xml
Labels: fix

#163 🔀 :: (#161) - 외출 삭제 아이콘은 어드민에게만 보임
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
Labels: fix

#169 🔀 :: (#168) - 외출리스트에서 학생을 삭제 했을때 즉시 적용
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
Labels: fix
