Repository team-haribo/GOMS-Android, pull requests merged in 2023-05, with the labels that each got.

#22 🔀 :: (#21) - Sign In 구현
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/goms/data/api/AuthApi.kt
  data/src/main/java/com/goms/data/api/SignInService.kt
  data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
  data/src/main/java/com/goms/data/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/goms/data/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/goms/data/datasource/token/AuthTokenDataSource.kt
  data/src/main/java/com/goms/data/datasource/token/AuthTokenDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/AuthMapper.kt
  data/src/main/java/com/goms/data/mapper/ProfileMapper.kt
  data/src/main/java/com/goms/data/model/auth/request/SignInRequest.kt
  data/src/main/java/com/goms/data/model/auth/response/RefreshTokenResponse.kt
  data/src/main/java/com/goms/data/model/auth/response/SignInResponse.kt
  data/src/main/java/com/goms/data/model/profile/response/ProfileResponse.kt
  data/src/main/java/com/goms/data/model/signin/response/SignInResponse.kt
  data/src/main/java/com/goms/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/goms/data/repository/SignInRepositoryImpl.kt
  data/src/main/java/com/goms/data/source/SignInDataSource.kt
  data/src/main/java/com/goms/data/source/SignInDataSourceImpl.kt
  domain/src/main/java/com/goms/domain/data/profile/response/ProfileResponseData.kt
  domain/src/main/java/com/goms/domain/data/signin/response/SignInResponseData.kt
  domain/src/main/java/com/goms/domain/exception/HttpException.kt
  domain/src/main/java/com/goms/domain/exception/NeedLoginException.kt
  domain/src/main/java/com/goms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/goms/domain/repository/SignInRepository.kt
  domain/src/main/java/com/goms/domain/usecase/auth/CheckLoginUseCase.kt
  domain/src/main/java/com/goms/domain/usecase/auth/SetTokenUseCase.kt
  domain/src/main/java/com/goms/domain/usecase/auth/SignInUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/goms/presentation/di/module/DataSourceModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/RepositoryModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
  presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/SplashViewModel.kt
  presentation/src/main/res/drawable/goms_buttom_background.xml
  presentation/src/main/res/drawable/goms_logo.png
  presentation/src/main/res/drawable/goms_logo.xml
  presentation/src/main/res/drawable/goms_splash_logo.png
  presentation/src/main/res/drawable/goms_splash_logo.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_sign_in.xml
  presentation/src/main/res/layout/activity_splash.xml
  presentation/src/main/res/values/attrs.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/themes.xml
Labels: feature

#24 🔀 :: (#23) - 프로필 기능 구현
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/goms/data/api/ProfileApi.kt
  data/src/main/java/com/goms/data/datasource/profile/ProfileDataSource.kt
  data/src/main/java/com/goms/data/datasource/profile/ProfileDataSourceImpl.kt
  data/src/main/java/com/goms/data/model/profile/response/StudentInfo.kt
  data/src/main/java/com/goms/data/repository/ProfileRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/profile/response/StudentInfoData.kt
  domain/src/main/java/com/goms/domain/repository/ProfileRepository.kt
  domain/src/main/java/com/goms/domain/usecase/profile/ProfileUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/goms/presentation/di/module/DataSourceModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/RepositoryModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
  presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/ProfileViewModel.kt
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/fragment_home.xml
Labels: feature

#26 🔀 :: (#25) - http 인터셉터 리팩토링
  data/src/main/java/com/goms/data/api/ProfileApi.kt
  data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
  data/src/main/java/com/goms/data/datasource/profile/ProfileDataSource.kt
  data/src/main/java/com/goms/data/datasource/profile/ProfileDataSourceImpl.kt
  data/src/main/java/com/goms/data/repository/ProfileRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/repository/ProfileRepository.kt
  domain/src/main/java/com/goms/domain/usecase/profile/ProfileUseCase.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
Labels: refactoring

#28 🔀 :: (#27) - 프로필 데이터 전달 기능 핫픽스
  domain/src/main/java/com/goms/domain/data/profile/response/ProfileResponseData.kt
  domain/src/main/java/com/goms/domain/data/profile/response/StudentInfoData.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
  presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
  presentation/src/main/res/layout/activity_profile.xml
Labels: refactoring

#30 🔀 :: (#29) - 파일 구조 변경(핫픽스)
  data/src/main/java/com/goms/data/api/ProfileApi.kt
  data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
  data/src/main/java/com/goms/data/datasource/profile/ProfileDataSource.kt
  data/src/main/java/com/goms/data/datasource/profile/ProfileDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/AuthMapper.kt
  data/src/main/java/com/goms/data/mapper/ProfileMapper.kt
  data/src/main/java/com/goms/data/model/profile/ProfileResponse.kt
  data/src/main/java/com/goms/data/model/profile/StudentInfo.kt
  data/src/main/java/com/goms/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/auth/request/SignInRequestData.kt
  domain/src/main/java/com/goms/domain/data/auth/response/SignInResponseData.kt
  domain/src/main/java/com/goms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/goms/domain/usecase/auth/SignInUseCase.kt
  presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
Labels: hotfix

#32 🔀 :: (#31) - outing 로직 구현
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/goms/data/api/OutingApi.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/OutingMapper.kt
  data/src/main/java/com/goms/data/model/outing/OutingCountResponse.kt
  data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/outing/OutingCountResponseData.kt
  domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
  domain/src/main/java/com/goms/domain/usecase/outing/OutingCountUseCase.kt
  domain/src/main/java/com/goms/domain/usecase/outing/OutingListUseCase.kt
  domain/src/main/java/com/goms/domain/usecase/outing/OutingUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/goms/presentation/di/module/DataSourceModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/RepositoryModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
Labels: feature

#34 🔀 :: (#31) - 지각 랭킹 구현
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/goms/data/api/LateApi.kt
  data/src/main/java/com/goms/data/datasource/late/LateDataSource.kt
  data/src/main/java/com/goms/data/datasource/late/LateDataSourceImpl.kt
  data/src/main/java/com/goms/data/model/profile/ProfileResponse.kt
  data/src/main/java/com/goms/data/repository/LateRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/repository/LateRepository.kt
  domain/src/main/java/com/goms/domain/usecase/late/LateUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/goms/presentation/di/module/DataSourceModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/RepositoryModule.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/home/component/HomeItemCard.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/fragment_home.xml
Labels: feature

#36 🔀 :: (#33) - 외출 상태 관리 로직 추가
  data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
  data/src/main/java/com/goms/data/repository/AuthRepositoryImpl.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
  presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
  presentation/src/main/res/layout/fragment_home.xml
Labels: feature

#38 🔀 :: (#37) - 지각자 랭킹 리스트가 비어 있을 때의 화면 추가
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/home/component/LateRankEmptyScreen.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
  presentation/src/main/res/drawable/goms_buttom_background.xml
  presentation/src/main/res/drawable/mind_fulness.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/values-v31/splash_theme.xml
  presentation/src/main/res/values/colors.xml
Labels: feature

#40 🔀 :: (#39) - 외출하기 로직 변경
  data/src/main/java/com/goms/data/api/OutingApi.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
  data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
  domain/src/main/java/com/goms/domain/usecase/outing/OutingUseCase.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
Labels: refactoring

#42 🔀 :: (#41) - admin 페이지 퍼블리싱
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/goms/presentation/utils/CheckRole.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/home/component/HomeItemCard.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageSearchTextField.kt
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
  presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/ProfileViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
  presentation/src/main/res/color/bottom_navi_item_selector.xml
  presentation/src/main/res/drawable/admin_attribute_button_selected.xml
  presentation/src/main/res/drawable/admin_attribute_button_unselected.xml
  presentation/src/main/res/drawable/admin_filter_background.xml
  presentation/src/main/res/drawable/backarrow_left.xml
  presentation/src/main/res/drawable/baseline_search_24.xml
  presentation/src/main/res/drawable/mind_fulness.xml
  presentation/src/main/res/drawable/pencil_icon.xml
  presentation/src/main/res/drawable/qr_code_scan_icon.xml
  presentation/src/main/res/drawable/shopping_bags_tdby.xml
  presentation/src/main/res/drawable/working_re_ddwy.xml
  presentation/src/main/res/layout/activity_student_manage.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/menu/bottom_navi_item.xml
  presentation/src/main/res/values/colors.xml
Labels: publishing

#44 🔀 :: (#43) - 학번 이슈 수정
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
Labels: fix

#46 🔀 :: (#45) - 외출 list return type 변경
  data/src/main/java/com/goms/data/api/OutingApi.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/UserMapper.kt
  data/src/main/java/com/goms/data/model/user/UserInfo.kt
  data/src/main/java/com/goms/data/model/user/UserResponse.kt
  data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/user/UserInfoData.kt
  domain/src/main/java/com/goms/domain/data/user/UserResponseData.kt
  domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
  domain/src/main/java/com/goms/domain/usecase/outing/OutingListUseCase.kt
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
Labels: refactoring

#52 🔀 :: (#51) - 학생 권한 수정 기능 구현
  data/src/main/java/com/goms/data/api/CouncilApi.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/CouncilMapper.kt
  data/src/main/java/com/goms/data/model/council/ModifyRoleRequest.kt
  data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/goms/domain/data/council/ModifyRoleRequestData.kt
  domain/src/main/java/com/goms/domain/exception/HttpException.kt
  domain/src/main/java/com/goms/domain/exception/OtherException.kt
  domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
  domain/src/main/java/com/goms/domain/usecase/admin/ModifyRoleUseCase.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
  presentation/src/main/res/layout/activity_student_manage.xml
Labels: feature

#54 🔀 :: (#53) - http 통신 response 실패 시 로직 변경
  domain/src/main/java/com/goms/domain/exception/HttpException.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/ProfileViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
Labels: refactoring

#56 🔀 :: (#55) - 외출 금지 기능 구현
  data/src/main/java/com/goms/data/api/CouncilApi.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
  data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
  domain/src/main/java/com/goms/domain/usecase/admin/SetBlackListUseCase.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
Labels: feature

#58 🔀 :: (#57) - 기존 바텀 시트 dialog fragment로 적용
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/FilterBottomSheetDialog.kt
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/ModifyRoleBottomSheetDialog.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageSearchTextField.kt
  presentation/src/main/res/drawable/bottom_sheet_filter_edit_text_bg.xml
  presentation/src/main/res/layout/activity_student_manage.xml
  presentation/src/main/res/layout/bottom_sheet_filter.xml
  presentation/src/main/res/layout/bottom_sheet_modify_role.xml
  presentation/src/main/res/values/themes.xml
Labels: refactoring

#62 🔀 :: (#61) - qr code 생성 로직 구현
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/goms/data/api/CouncilApi.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
  data/src/main/java/com/goms/data/model/council/response/MakeQrCodeResponse.kt
  data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/council/response/MakeQrCodeResponseData.kt
  domain/src/main/java/com/goms/domain/exception/HttpException.kt
  domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
  domain/src/main/java/com/goms/domain/usecase/admin/MakeQrCodeUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_student_manage.xml
  presentation/src/main/res/layout/fragment_qr_scan.xml
Labels: feature

#64 🔀 :: (#63) - goms custom dialog 구현
  domain/src/main/java/com/goms/domain/usecase/admin/SetBlackListUseCase.kt
  presentation/src/main/java/com/goms/presentation/utils/GomsDialog.kt
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/ModifyRoleBottomSheetDialog.kt
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
  presentation/src/main/res/drawable/dialog_bg.xml
  presentation/src/main/res/drawable/dialog_button_bg_no.xml
  presentation/src/main/res/layout/goms_dialog.xml
Labels: feature

#66 🔀 :: (#65) - 중복된 data class 정리
  data/src/main/java/com/goms/data/mapper/CouncilMapper.kt
  data/src/main/java/com/goms/data/mapper/ProfileMapper.kt
  data/src/main/java/com/goms/data/mapper/UserMapper.kt
  data/src/main/java/com/goms/data/mapper/util/StudentInfoMapper.kt
  data/src/main/java/com/goms/data/model/council/response/SearchStudentResponse.kt
  data/src/main/java/com/goms/data/model/profile/ProfileResponse.kt
  data/src/main/java/com/goms/data/model/profile/StudentInfo.kt
  data/src/main/java/com/goms/data/model/user/UserResponse.kt
  data/src/main/java/com/goms/data/model/util/StudentInfo.kt
  domain/src/main/java/com/goms/domain/data/council/response/SearchStudentResponseData.kt
  domain/src/main/java/com/goms/domain/data/profile/ProfileResponseData.kt
  domain/src/main/java/com/goms/domain/data/user/UserInfoData.kt
  domain/src/main/java/com/goms/domain/data/user/UserResponseData.kt
  domain/src/main/java/com/goms/domain/data/util/StudentInfoData.kt
Labels: refactoring

#68 🔀 :: (#67) - 학생 리스트 api data response 변경
  data/src/main/java/com/goms/data/api/CouncilApi.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/CouncilMapper.kt
  data/src/main/java/com/goms/data/model/council/response/UserListResponse.kt
  data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/council/response/UserListResponseData.kt
  domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
  domain/src/main/java/com/goms/domain/usecase/admin/UserListUseCase.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
  presentation/src/main/res/values/colors.xml
Labels: refactoring

#70 🔀 :: (#69) - 검색 filter 검색 조건 확장
  data/src/main/java/com/goms/data/api/CouncilApi.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/CouncilMapper.kt
  data/src/main/java/com/goms/data/model/council/response/SearchStudentResponse.kt
  data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/council/response/SearchStudentResponseData.kt
  domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
  domain/src/main/java/com/goms/domain/usecase/admin/SearchStudentUseCase.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/SearchFilterBottomSheetDialog.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
  presentation/src/main/res/layout/bottom_sheet_search_filter.xml
Labels: refactoring

#72 🔀 :: (#71) - ci 세팅
  .github/workflows/android.yml
Labels: feature

#75 🔀 :: (#74) - pr, bug template 추가
  .github/ISSUE_TEMPLATE/bug.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature

#77 🔀 :: (#76) - 메인 화면 잔이슈 수정
  domain/src/main/java/com/goms/domain/data/util/StudentInfoData.kt
  presentation/src/main/ic_launcher-playstore.png
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/res/drawable-v24/ic_launcher_foreground.xml
  presentation/src/main/res/drawable/goms_app_logo.xml
  presentation/src/main/res/drawable/ic_launcher_background.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  presentation/src/main/res/mipmap-hdpi/ic_launcher.png
  presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher.png
  presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  presentation/src/main/res/values/ic_launcher_background.xml
  presentation/src/main/res/values/strings.xml
Labels: fix

#79 🔀 :: (#78) - qr scan 재퍼블리싱
  presentation/src/main/res/layout/fragment_qr_scan.xml
Labels: publishing

#94 🔀 :: (#80) - 화면 전환 시 에러 수정
  presentation/src/main/AndroidManifest.xml
Labels: fix

#95 🔀 :: (#81) modify back arrow area
  presentation/src/main/res/drawable/back_arrow_black.xml
  presentation/src/main/res/drawable/left_arrow_black.xml
  presentation/src/main/res/drawable/left_arrow_white.xml
  presentation/src/main/res/drawable/right_arrow_orange.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_qr_code.xml
  presentation/src/main/res/layout/activity_student_manage.xml
  presentation/src/main/res/layout/fragment_home.xml
Labels: fix

#96 🔀 :: (#83) - 다이얼로그 버튼 색상 적용 이슈 해결
  presentation/src/main/res/drawable/dialog_button_bg_yes.xml
  presentation/src/main/res/layout/goms_dialog.xml
Labels: fix

#97 🔀 :: (#85) add qr timer
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
  presentation/src/main/res/layout/fragment_qr_scan.xml
Labels: feature

#98 🔀 :: (#88) set current authority
  data/src/main/java/com/goms/data/api/CouncilApi.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
  data/src/main/java/com/goms/data/mapper/CouncilMapper.kt
  data/src/main/java/com/goms/data/model/council/response/UserInfoResponse.kt
  data/src/main/java/com/goms/data/model/council/response/UserListResponse.kt
  data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/data/council/response/UserInfoResponseData.kt
  domain/src/main/java/com/goms/domain/data/council/response/UserListResponseData.kt
  domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
  domain/src/main/java/com/goms/domain/usecase/admin/SearchStudentUseCase.kt
  domain/src/main/java/com/goms/domain/usecase/admin/UserListUseCase.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/ModifyRoleBottomSheetDialog.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
  presentation/src/main/res/layout/bottom_sheet_modify_role.xml
Labels: bug, refactoring

#101 🔀 :: (#100) - 수정한 다이얼로그 버튼 색이 제데로 적용되지 않았던 오류 수정
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
Labels: fix

#102 🔀 :: (#91) - 외출 상태에 따라 button 텍스트 달라지지 않던 오류 수정
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
Labels: fix

#105 🔀 :: (#90) - 로딩 인디케이터 생성
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
  presentation/src/main/res/layout/activity_student_manage.xml
  presentation/src/main/res/layout/fragment_home.xml
  presentation/src/main/res/layout/fragment_outing.xml
  presentation/src/main/res/layout/fragment_qr_scan.xml
  presentation/src/main/res/layout/view_loading_indicator.xml
Labels: refactoring

#103 🔀 :: (#99) write readme
  LICENSE
  README.md
Labels: documentation

#107 🔀 :: (#86) updating when lazycolumn items change
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/res/layout/activity_student_manage.xml
Labels: feature

#108 🔀 :: (#104) - api 통신 시 에러 handling
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
  data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
  data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/exception/HttpException.kt
  domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
  domain/src/main/java/com/goms/domain/usecase/outing/OutingUseCase.kt
  presentation/src/main/java/com/goms/presentation/utils/ApiErrorHandling.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
  presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
  presentation/src/main/res/layout/fragment_qr_scan.xml
Labels: refactoring

#110 🔀 :: (#106) nested qr timer
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
Labels: fix

#111 🔀 :: (#107) - swipe refresh layout이 lazyColumn의 scroll을 막던 오류 수정
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/res/layout/activity_student_manage.xml
Labels: fix

#113 🔀 :: (#112) - qr scan 화면 생성
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/ScanCompleteFragment.kt
  presentation/src/main/res/drawable/completed.xml
  presentation/src/main/res/layout/fragment_scan_complete.xml
  presentation/src/main/res/navigation/bottom_navigation.xml
Labels: feature

#117 🔀 :: (#113) renew qr uuid
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
Labels: fix

#121 🔀 :: (#116) - 외출 금지 취소 기능 구현
  data/src/main/java/com/goms/data/api/CouncilApi.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
  data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
  data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
  domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
  domain/src/main/java/com/goms/domain/usecase/admin/CancelBlackListUseCase.kt
  presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
  presentation/src/main/java/com/goms/presentation/utils/GomsDialog.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
  presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
  presentation/src/main/res/drawable/figure_run_circle.xml
Labels: feature

#122 🔀 :: (#118) - device마다 적절하게 view 크기 변경하기
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/home/component/HomeItemCard.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/ScanCompleteFragment.kt
Labels: refactoring

#126 🔀 :: (#115) cd setting
  .github/workflows/android-cd.yml
  .github/workflows/android-ci.yml
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/src/androidTest/java/com/goms/data/ExampleInstrumentedTest.kt
  data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
  domain/build.gradle.kts
  domain/src/androidTest/java/com/goms/domain/ExampleInstrumentedTest.kt
  presentation/.gitignore
  presentation/build.gradle.kts
  presentation/google-services.json.gpg
  presentation/src/androidTest/java/com/goms/presentation/ExampleInstrumentedTest.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
  presentation/src/main/java/com/goms/presentation/utils/GomsBlackListDialog.kt
  presentation/src/main/java/com/goms/presentation/utils/GomsDialog.kt
  presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
  presentation/src/main/java/com/goms/presentation/view/home/component/HomeItemCard.kt
  presentation/src/main/java/com/goms/presentation/view/home/component/LateRankEmptyScreen.kt
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/ModifyRoleBottomSheetDialog.kt
  presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/SearchFilterBottomSheetDialog.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/SearchResultEmptyScreen.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
  presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
  presentation/src/main/java/com/goms/presentation/view/outing/component/EmptyScreen.kt
  presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
  presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/ScanCompleteFragment.kt
  presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
  presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
Labels: feature

#128 🔀 :: (#125) - 간단한 UI 수정
  presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
  presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
  presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/ScanCompleteFragment.kt
  presentation/src/main/res/drawable/figure_run_circle.xml
  presentation/src/main/res/drawable/manage_black_list.xml
Labels: refactoring

#129 🔀 :: (#127) Toast 메시지 계속 뜨던 에러 고치기
  presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
Labels: fix
